version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - default-network
    volumes:
      - type: volume
        source: minio_data
        target: /data
    command: server /data --console-address ":9001"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    container_name: api
    networks:
      - default-network
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules

volumes:
  postgres_data:
  minio_data:

networks:
  default-network:
    driver: bridge
    external: true
