version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    container_name: api
    networks:
      - default-network
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  default-network:
    driver: bridge
    external: true
